Edit title
patrickchin/haru2-vercel pull request #2
Opened 2024-04-29 16:05 UTC by binayak20

2024-04-29 16:32 UTC, patrickchin requested changes

2024-04-29 16:32 UTC, patrickchin commented on components/editable-title.tsx
> +  function clickDeleteProject() {
wrong function name

2024-04-29 16:32 UTC, patrickchin commented on pnpm-lock.yaml
not sure what these changes are! can be done in another PR

2024-04-29 16:32 UTC, patrickchin commented on components/editable-title.tsx
> +    redirect("/projects");
router.refresh might be better

2024-04-29 16:32 UTC, patrickchin commented on components/editable-title.tsx
> +        defaultValue={title}
can set max length to 255

2024-04-29 16:32 UTC, patrickchin commented on components/editable-title.tsx
>          <LucidePencil className="fg-muted w-4 p-0 opacity-40 hover:opacity-100" />
I think we don't need to show this icon when editing

2024-04-29 16:32 UTC, patrickchin commented on components/editable-title.tsx
> +        variant="ghost"
when editing maybe make these buttons more visible, maybe variant="outline" and not a muted foreground?

2024-04-29 16:32 UTC, patrickchin commented on components/editable-title.tsx
> +        onClick={() => setEditing(!editing)}
this will need to revert the current visible title back to the original title

2024-04-29 16:32 UTC, patrickchin commented on lib/db.ts
what formatter are you using? what are your settings? They are ok, I don't disagree with them but it would be good to have the same formatter settings

2024-04-29 16:37 UTC, patrickchin commented on components/editable-title.tsx
> +    redirect("/projects");
I'm ok with a refresh, but I'm wondering if it's necessary

2024-04-29 16:53 UTC, patrickchin commented on components/editable-title.tsx
> +    updateProjectTitle(project.id, title)
should this be awaited before calling redirect below?

2024-04-30 02:21 UTC, binayak20 commented on lib/db.ts
Can you please send the the setting.json file? I can not find this file and can not set the same formatting

2024-04-30 06:04 UTC, patrickchin requested changes
still a few comments to be resolved and we can get this merged

2024-04-30 06:04 UTC, patrickchin commented on pnpm-lock.yaml
remove these changes please!

2024-04-30 06:04 UTC, patrickchin commented on components/editable-title.tsx
> +    redirect("/projects");
replace this with a router.refresh

2024-04-30 06:06 UTC, patrickchin commented on lib/db.ts
Ooh, i see you are using prettier 👍

2024-04-30 06:38 UTC, binayak20 commented on components/editable-title.tsx
> +      {!editing && (
Sorry about this kind of stupid un-necessary code.

2024-04-30 07:36 UTC, patrickchin approved these changes

2024-04-30 07:37 UTC, patrickchin commented
LGTM

2024-04-30 07:37 UTC, merged